// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACO0UDRlyMKXQtfA_zASE-RofO5KWdb48',
    appId: '1:1013890905953:web:89a718002f0e4641453720',
    messagingSenderId: '1013890905953',
    projectId: 'brewcrew-a72ed',
    authDomain: 'brewcrew-a72ed.firebaseapp.com',
    storageBucket: 'brewcrew-a72ed.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXlJstsq6ttlT5gF8bCiMcNQTCsu2UbJA',
    appId: '1:1013890905953:android:1a7c66a7c984c411453720',
    messagingSenderId: '1013890905953',
    projectId: 'brewcrew-a72ed',
    storageBucket: 'brewcrew-a72ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOL065tdwf_V2ICpRBueprC4wZ9-dKMh4',
    appId: '1:1013890905953:ios:7a30df625dbd0daf453720',
    messagingSenderId: '1013890905953',
    projectId: 'brewcrew-a72ed',
    storageBucket: 'brewcrew-a72ed.firebasestorage.app',
    iosBundleId: 'com.example.brewCrew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOL065tdwf_V2ICpRBueprC4wZ9-dKMh4',
    appId: '1:1013890905953:ios:7a30df625dbd0daf453720',
    messagingSenderId: '1013890905953',
    projectId: 'brewcrew-a72ed',
    storageBucket: 'brewcrew-a72ed.firebasestorage.app',
    iosBundleId: 'com.example.brewCrew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACO0UDRlyMKXQtfA_zASE-RofO5KWdb48',
    appId: '1:1013890905953:web:6c297b40998244e1453720',
    messagingSenderId: '1013890905953',
    projectId: 'brewcrew-a72ed',
    authDomain: 'brewcrew-a72ed.firebaseapp.com',
    storageBucket: 'brewcrew-a72ed.firebasestorage.app',
  );
}
